name: Tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-22.04

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: chats_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4
      - name: setup-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      - name: install dependencies
        run: composer install --no-interaction --prefer-dist

      - name: copy .env
        run: cp .env.example .env

      - name: generate key
        run: php artisan key:generate

      - name: run-test
        run: php artisan test
        env:
          DB_CONNECTION: pgsql
          DB_HOST: 127.0.0.1
          DB_PORT: 5432
          DB_DATABASE: chats_test
          DB_USERNAME: postgres
          DB_PASSWORD: password
